# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gMp7qyglE3qDftbl8AKpf3Yixle2kydq
"""

# app.py
!pip install streamlit

import streamlit as st
import pandas as pd
import numpy as np
import joblib
from sklearn.datasets import load_iris
import seaborn as sns
import matplotlib.pyplot as plt

# Load model dan dataset
model = joblib.load('naive_bayes_iris.pkl')
iris = load_iris()
df = pd.DataFrame(iris.data, columns=iris.feature_names)
df['target'] = iris.target
df['target_name'] = df['target'].apply(lambda x: iris.target_names[x])

# Sidebar untuk navigasi
st.sidebar.title("🧪 Iris Classifier")
page = st.sidebar.radio("Pilih Halaman", ["📄 Deskripsi Data", "🔮 Prediksi", "📊 Visualisasi"])

# Halaman 1: Deskripsi Data
if page == "📄 Deskripsi Data":
    st.title("📄 Deskripsi Dataset Iris")
    st.markdown("""
    Dataset Iris adalah kumpulan data klasik yang sering digunakan untuk masalah klasifikasi.
    Dataset ini berisi 150 data bunga iris dengan fitur:
    - Panjang dan lebar sepal
    - Panjang dan lebar petal

    Tiga jenis bunga iris:
    - Setosa
    - Versicolor
    - Virginica
    """)
    st.dataframe(df.head())
    st.write("Distribusi Kelas:")
    st.bar_chart(df['target_name'].value_counts())

# Halaman 2: Prediksi
elif page == "🔮 Prediksi":
    st.title("🔮 Prediksi Spesies Iris")
    st.write("Masukkan data bunga di bawah ini:")

    # Input fitur
    sepal_length = st.slider('Panjang Sepal (cm)', 4.0, 8.0, 5.0)
    sepal_width = st.slider('Lebar Sepal (cm)', 2.0, 4.5, 3.0)
    petal_length = st.slider('Panjang Petal (cm)', 1.0, 7.0, 4.0)
    petal_width = st.slider('Lebar Petal (cm)', 0.1, 2.5, 1.0)

    # Prediksi
    input_data = np.array([[sepal_length, sepal_width, petal_length, petal_width]])
    prediction = model.predict(input_data)[0]
    prediction_proba = model.predict_proba(input_data)[0]

    st.success(f"Prediksi: **{iris.target_names[prediction].capitalize()}**")
    st.subheader("Probabilitas:")
    st.bar_chart({
        'Setosa': [prediction_proba[0]],
        'Versicolor': [prediction_proba[1]],
        'Virginica': [prediction_proba[2]],
    })

# Halaman 3: Visualisasi
else:
    st.title("📊 Visualisasi Data Iris")
    st.write("Scatter plot fitur untuk melihat pola antara spesies.")

    fig, axes = plt.subplots(1, 2, figsize=(12, 5))

    sns.scatterplot(ax=axes[0], data=df, x=iris.feature_names[0], y=iris.feature_names[1],
                    hue='target_name', palette='Set2')
    axes[0].set_title("Sepal: Panjang vs Lebar")

    sns.scatterplot(ax=axes[1], data=df, x=iris.feature_names[2], y=iris.feature_names[3],
                    hue='target_name', palette='Set1')
    axes[1].set_title("Petal: Panjang vs Lebar")

    st.pyplot(fig)